apiVersion: "spec.keptn.sh/0.2.2"
kind: "Shipyard"
metadata:
  name: "shipyard-easytravel"
spec:
  stages:
    - name: "production"
      sequences:
      - name: "auto_healing_memory"
        tasks:
        - name: toggle_featureflag
        - name: evaluation
          triggeredAfter: "5m"
          properties:
                timeframe: "2m"
      - name: "auto_healing_memory_remediation_failed"
        triggeredon: auto_healing_memory result = "fail"
        tasks:
        - name: restart
        - name: evaluation
          triggeredAfter: "2m"
          properties:
              timeframe: "2m"
   - name: "production-disk"
     sequences:
      - name: "auto_healing_disk"
        tasks:
        - name: clean_disk
        - name: evaluation
          triggeredAfter: "5m"
          properties:
            timeframe: "2m"
      - name: "auto_healing_memory_remediation_failed"
        triggeredon: auto_healing_disk result = "fail"
        tasks:
        - name: escalate_human



